### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by dholms** [jasondavies/bloomfilter.js#31] opened 2020-08-11 01:03 UTC
I'm getting a much higher false positive rate than I would expect from a bloom filter of the size that I'm using

I'm using a 1024-bit bloomfilter with 16 hashes and 20 elements in each filter.

I'm running a test which adds 20 elements to a filter, checking before adding each that the item isn't already in the filter.

After running the test 500 times, there are ~4 collisions.

Given a bloom filter with those parameters, there should only be about a 1/1.3 billion chance of collision (https://hur.st/bloomfilter/?n=20&p=&m=1024&k=16)

Here's the short script:
```js
    let collisions = 0
    for(let i=0; i< 500; i++) {
      const filter = new BloomFilter(1024, 16)
      const dict = {}
      for(let j=0; j< 20; j++) {
        const str = Math.floor(Math.random() * 1000000000).toString(16)
        if(filter.test(str) && dict[str] !== true){
          console.log("COLLISION: ", str)
          collisions++
        }
        filter.add(str)
        dict[str] = true
      }
      console.log(i)
    }
    console.log('done: ', collisions)
```

**Comment by jasondavies** [comment] 2020-08-11 12:25
Interesting.  The only way I was able to fix this was by using *k* independent hash functions, instead of the current version which uses 2 independent hash functions `a` and `b` internally, and combines them to generate *k* hash functions using:

    h_i(d) = a(d) + i * b(d)

As far as I know this is common practice, and the idea is mentioned in [Building a Better Bloom Filter](https://www.eecs.harvard.edu/~michaelm/postscripts/tr-02-05.pdf).  I'm guessing that this optimisation has some effect on the false positive rate as the *k* hash functions are not completely independent.

**Comment by jasondavies** [comment] 2020-08-11 13:03
Perhaps @Gopiandcode would be interested in this.  He is the author of [Bloom filters debunked: Dispelling 30 Years of bad math with Coq!
](https://gopiandcode.uk/logs/log-bloomfilters-debunked.html)

**Comment by k15a** [comment] 2020-12-14 21:08
I think the problem is that you are effectively only using a single hash function:

In the [bloomfilter.js](https://github.com/jasondavies/bloomfilter.js/blob/master/bloomfilter.js#L41-L42) file you have the following:

```js
a = fnv_1a(v),
b = fnv_1a(v, 1576284489), // The seed value is chosen randomly
```

Where `a` is supposed to be the first hash and `b` is a second hash to create a any number of hashes described in https://willwhim.wpengine.com/2011/09/03/producing-n-hash-functions-by-hashing-only-once/

I think the problem is that when using two different hash functions the value of the hashes `a` and `b` will be independent but in your case if two values `v` generate the same hash `a` the second hash `b` will also be the same and therefore any any hash created by the method above will also be the same.

**Comment by nponeccop** [comment] 2023-03-24 13:33
I'd suggest you try the benchmarking using a CSRNG from `crypto` instead of `Math.random()`. With such complex bit patterns, the randomness provided by simple RNGs is often not enough.

**Comment by DavidBuchanan314** [comment] 2024-12-17 22:39
The issue lies here:

https://github.com/jasondavies/bloomfilter.js/blob/fbc89107b5aec93918e5017f4b15c38f11389e6b/bloomfilter.js#L41-L47

if b%m=0, (probaility 1/m) then all indices generated will be equal, skyrocketing the collision probability.

**Comment by jasondavies** [comment] 2024-12-17 23:17
Good catch.

**Comment by DavidBuchanan314** [comment] 2024-12-17 23:30
A quick fix would be `b = (b % (m - 1)) + 1` just after line 42 (essentially, making b%m=0 impossible)

**Closed** 2024-12-18 00:57 UTC
