### ISSUE TITLE
bloom.buckets doesn't work

### ISSUE THREAD

**Issue by Agipa** [jasondavies/bloomfilter.js#30] opened 2019-10-01 02:49 UTC
Hello! 
var array = [].slice.call(bloom.buckets),
      json = JSON.stringify(array);

This method doesn't work. How I can get serialization in your package? bloom method doesn't identify the buckets. It only hash bitview, view, serialize, and etc.

**Comment by jasondavies** [comment] 2024-12-18 11:08
It does work if you follow the example in the README, but admittedly the API could be friendlier.  Duplicate of #16.

**Closed by jasondavies** 2024-12-18 11:08 UTC
